name: lpg_delivery_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  http: ^1.4.0
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.2.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_spinkit: ^5.2.0
  flutter_plugin_android_lifecycle: ^2.0.28
  get_storage: ^2.1.1
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  location: ^5.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  audioplayers: ^5.2.1
  flutter_typeahead: ^4.0.0
  url_launcher: ^6.1.11








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1


flutter:

  # Enables Material Design icons
  uses-material-design: true

  # Asset configuration
  assets:
    - assets/images/


flutter_native_splash:
  color: "#3E3EFF"
  image: assets/images/delivery.png
  android: true
  ios: true
  web: false
  android_gravity: center
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/branding.png"
  remove_alpha_ios: true
